select * from customer;

#Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender;


#Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id , purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount>=(select avg(purchase_amount) from customer);


#Q3. Which are the top 10 products with the highest average ratning?
select item_purchased , avg(review_rating) as 'avrage_rating'
from customer
group by item_purchased
order by avg(review_rating) desc
limit 10;


# Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type , avg(purchase_amount)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;


# Q5. Do subscribed customers spend more? Compare average spend and total revenue 
# between subscribers and non-subscribers.
select count(customer_id) as total_customers ,avg(purchase_amount) as avg_spend , sum(purchase_amount) as total_spend , subscription_status
from customer
group by subscription_status;


# Q6. Which 10 products have the highest percentage of purchases with discounts applied?
select item_purchased, 100*sum(case when discount_applied = "Yes" then 1 else 0 end)/ count(*)  as discount_percentage
from customer
group by item_purchased
order by discount_percentage desc
limit 10;


# Q7. Segment customers into New, Returning, and Loyal based on their total 
# number of previous purchases, and show the count of each segment. 
with my_cte as (
select customer_id, previous_purchases, 
case 
	when previous_purchases <= 1 then 'New'
    when previous_purchases <= 15 then 'Returning'
    Else 'Loyal'
END as type_of_customer
From customer
)
select type_of_customer, count(*) as "number_of_customers" 
from my_cte
group by type_of_customer;


# Q8. What are the top 5 most purchased products within each category?
with item_counts as (
    select category,
           item_purchased,
           count(customer_id) as total_orders,
           row_number() over (partition by category order by count(customer_id) desc) as item_rank
    from customer
    group by category, item_purchased
)
select item_rank,category, item_purchased, total_orders
from item_counts
where item_rank <=3;


# Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers from customer
where previous_purchases > 5
group by subscription_status;


# Q10. What is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as revenue_contribution 
from customer 
group by age_grou;








